spring.application.name=ordenes_trabajo_backend
# Server Configuration
server.port=8080
server.servlet.context-path=/api

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://dereckvergara12_db_user:iZlslAMpNCCWg035@ordenestrabajo.mongodb.net/ordenestrabajo_db?retryWrites=true&w=majority
spring.data.mongodb.database=ordenestrabajo_db

# JWT Configuration
jwt.secret=TuClaveSecretaSuperSeguraDe32Caracteres1234567890
jwt.expiration=86400000 # 24 horas en milisegundos

# CORS Configuration
cors.allowed-origins=http://localhost:4200
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method